<?xml version="1.0"?>
<package format="3">
  <name>ghost_mgg_sim</name>
  <version>0.0.1</version>
  <description>Simulation worlds and adapters for GHOST-MGG.</description>
  <maintainer email="693180059@qq.com">runfengling</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>control_msgs</exec_depend>
  <exec_depend>controller_manager</exec_depend>
  <depend>geometry_msgs</depend>
  <exec_depend>ghost_mgg_mycobot_description</exec_depend>
  <exec_depend>gz_ros2_control</exec_depend>
  <depend>ghost_mgg_interfaces</depend>
  <exec_depend>joint_state_broadcaster</exec_depend>
  <exec_depend>joint_trajectory_controller</exec_depend>
  <depend>rclcpp</depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>visualization_msgs</depend>
  <exec_depend>xacro</exec_depend>
  <test_depend>ament_cmake_gtest</test_depend>
  <test_depend>ament_cmake_pytest</test_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
