<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ghost_mgg_real</name>
  <version>0.0.0</version>
  <description>Real hardware bringup assets for GHOST-MGG sensors and robot-side validation.</description>
  <maintainer email="693180059@qq.com">runfengling</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>realsense2_camera</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>ghost_mgg_interfaces</exec_depend>
  <exec_depend>ghost_mgg_core</exec_depend>
  <exec_depend>ghost_mgg_sim</exec_depend>

  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>ghost_mgg_core</test_depend>
  <test_depend>ghost_mgg_sim</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
