<?xml version="1.0"?>
<package format="3">
  <name>ghost_mgg_bringup</name>
  <version>0.0.1</version>
  <description>Launch and config entrypoints for GHOST-MGG.</description>
  <maintainer email="693180059@qq.com">runfengling</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>ghost_mgg_backends</exec_depend>
  <exec_depend>ghost_mgg_bt</exec_depend>
  <exec_depend>ghost_mgg_moveit_config</exec_depend>
  <exec_depend>ghost_mgg_sim</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>tf2_ros</exec_depend>

  <test_depend>ament_cmake_pytest</test_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
